# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false 
r_check_args: #--as-cran

addons:
  apt:
    packages:
      - libxml2-dev
      - gfortran
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - g++-7
  homebrew:
    packages:
      - libxml2
      - gcc
    update: true

before_install:
  - mkdir -p ~/.R
  - echo 'CXX17 = g++-7 -std=gnu++17 -fPIC' > ~/.R/Makevars

# Run on both linux and OS X
os:
  - linux
  - osx

env:
  - BADGE=linux
  - BADGE=osx

# hack to get some OS-specific badges
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux